SET(SOURCES ui_Screen1.c
    ui.c
    ui_comp_hook.c
    ui_helpers.c
    ui_img_1_png.c
    ui_img_25948186.c
    ui_img_2088487156.c
    ui_img_next_png.c
    ui_img_kyt_png.c
    ui_img_back_png.c
    ui_img_cancel_png.c
    ui_img_play_stop_png.c
    ui_img_3_png.c
    ui_img_5_png.c)

add_library(ui ${SOURCES})
