// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_1_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 800
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 480
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image2, &ui_img_25948186);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 150
lv_obj_set_x( ui_Image2, 294 );
lv_obj_set_y( ui_Image2, -30 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image3 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image3, &ui_img_2088487156);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 70
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_Image3, 298 );
lv_obj_set_y( ui_Image3, -155 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image4 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image4, &ui_img_next_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 70
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_Image4, 302 );
lv_obj_set_y( ui_Image4, 109 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image5 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image5, &ui_img_kyt_png);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 70
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_Image5, -347 );
lv_obj_set_y( ui_Image5, -174 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image6 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image6, &ui_img_back_png);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 40
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Image6, -348 );
lv_obj_set_y( ui_Image6, -96 );
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image7 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image7, &ui_img_cancel_png);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 70
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_Image7, -329 );
lv_obj_set_y( ui_Image7, 40 );
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image9 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image9, &ui_img_play_stop_png);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 70
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_Image9, -326 );
lv_obj_set_y( ui_Image9, 155 );
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


}
